### ISSUE TITLE
cannot build aegis frontend - fsevents library issues

### ISSUE THREAD

**Issue by o-alex** [aegisbigdata/hopsworks#19]
Cannot build the aegis-web module. When I try to build, I get an error while trying to make the fsevents library.

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/5680636/55069288-fa318d00-5083-11e9-89ea-a9f7d6cf05e2.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/5680636/55069292-fd2c7d80-5083-11e9-980c-cef72c364928.png">

**Comment by fabiankirstein** [comment]
@cbotsikas Do you have an idea?

**Comment by cbotsikas** [comment]
@FabiApfelkern @o-alex I think this is an issue in MacOS, something related with how node is installed via homebrew. Michael also had this issue. check slack #frontent on February 15th. I'm not sure if he managed to resolve it though. Can i see the output of the following commands:
`npm config get prefix`
`echo $NODE_PATH`
`echo $NODE_MODULES`
`which npm`

I think a possible solution would be: `npm config set prefix "/usr/local"` but this is just a speculation.

**Comment by cbotsikas** [comment]
Here are some related links:
https://github.com/h2non/requireg/issues/7
https://github.com/mjeanroy/bower-npm-resolver/issues/57
https://gist.github.com/DanHerbert/9520689 (Michael told me that following these instructions, he broke his system. I didn't have anymore news after that..)

**Comment by maismail** [comment]
@o-alex @cbotsikas @FabiApfelkern  the build works on my Mac. 
i exported the NODE_PATH in my .bashrc file
export NODE_PATH=/usr/local/lib/node_modules

**Comment by fabiankirstein** [comment]
@maismail Cool can you also deploy it then?

**Comment by maismail** [comment]
@FabiApfelkern will do it now. I already redeployed the landing page

**Comment by maismail** [comment]
@FabiApfelkern Done.

**Comment by fabiankirstein** [comment]
Thanks! It seems that our new aegis.css file was not included in the build. Do you have any idea if we have to configure something in the build process?

**Comment by fabiankirstein** [comment]
Wront alert. Need to clear the cache. Thanks  @cbotsikas

**Comment by cbotsikas** [comment]
@o-alex is this resolved for you? Shall we close it?
